# Configuration Supabase pour la plateforme d'inclusion numérique

[project]
ref = "votre-projet-ref"  # Remplacer par votre projet Supabase
name = "inclusion-numerique"
org = "ansut"
region = "eu-west-1"  # Région la plus proche de la Côte d'Ivoire

[database]
version = "15.1.0"
port = 5432

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]
jwt_expiry = 3600  # 1 heure
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change_enabled = true
template_confirm_signup = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Confirmation d'inscription - Plateforme d'Inclusion Numérique</title>
</head>
<body>
    <h1>Bienvenue sur la plateforme d'inclusion numérique !</h1>
    <p>Merci de vous inscrire. Veuillez confirmer votre adresse email en cliquant sur le lien ci-dessous :</p>
    <p><a href="{{ .ConfirmationURL }}">Confirmer mon email</a></p>
    <p>Ce lien expirera dans 24 heures.</p>
    <p>Si vous n'avez pas créé de compte, veuillez ignorer cet email.</p>
</body>
</html>
"""

[auth.sms]
enable_signup = true
enable_confirmations = true
template_confirm_signup = "Votre code de confirmation pour la plateforme d'inclusion numérique est {{ .Token }}"

[storage]
file_size_limit = 52428800  # 50MB
allowed_mime_types = [
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/webp",
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
]

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[analytics]
enabled = false

[experimental]
sso = false

# Configuration des variables d'environnement
[env.development]
[env.development.database]
pool_size = 10
pool_timeout = 30

[env.development.auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]

[env.production]
[env.production.database]
pool_size = 20
pool_timeout = 60

[env.production.auth]
site_url = "https://votre-domaine.com"
additional_redirect_urls = ["https://www.votre-domaine.com"]

# Configuration des webhooks (optionnel)
[webhooks]
enabled = false

# Configuration des fonctions edge (si nécessaire)
[functions]
enabled = false